name: LENS
channels:
  - conda-forge
  - defaults
dependencies:
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38haf1e3a3_1000
  - ca-certificates=2021.1.19=hecd8cb5_1
  - catalogue=1.0.0=py38_1
  - cffi=1.14.2=py38hed5b41f_0
  - chardet=3.0.4=py38_1003
  - conda=4.9.2=py38hecd8cb5_0
  - conda-package-handling=1.6.1=py38h1de35cc_0
  - cryptography=3.0=py38hddc9c9b_0
  - cycler=0.10.0=py_2
  - cython-blis=0.4.1=py38haf1e3a3_1
  - dask-core=2020.12.0=pyhd8ed1ab_0
  - decorator=4.4.2=py_0
  - freetype=2.10.4=h3f75d11_0
  - gmp=6.2.1=h23ab428_2
  - gmpy2=2.0.8=py38h6ef4df4_3
  - idna=2.10=py_0
  - importlib_metadata=1.7.0=0
  - intel-openmp=2019.4=233
  - ipython_genutils=0.2.0=py_1
  - joblib=0.16.0=py_0
  - jpeg=9d=hbcb3906_0
  - lcms2=2.11=h11f7e16_1
  - libcxx=11.0.0=h4c3b8ed_1
  - libedit=3.1.20191231=h1de35cc_1
  - libffi=3.3=hb1e8313_2
  - libgfortran=3.0.1=h93005f0_2
  - libllvm10=10.0.1=h009f743_3
  - libpng=1.6.37=h7cec526_2
  - libtiff=4.2.0=h355d032_0
  - libwebp-base=1.1.0=hbcb3906_3
  - llvm-openmp=10.0.0=h28b9765_0
  - llvmlite=0.34.0=py38h739e7dc_4
  - lz4-c=1.9.3=h046ec9c_0
  - matplotlib-base=3.3.3=py38h9bfd75d_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py38hfbe908c_0
  - mkl_fft=1.1.0=py38hc64f4ea_0
  - mkl_random=1.1.1=py38h959d312_0
  - mpc=1.1.0=h6ef4df4_1
  - mpfr=4.0.2=h9066e36_1
  - mpmath=1.1.0=py38_0
  - murmurhash=1.0.2=py38h0a44026_0
  - ncurses=6.2=h0a44026_1
  - numba=0.51.2=py38h6be0db6_0
  - numpy-base=1.19.1=py38hcfb5961_0
  - olefile=0.46=pyh9f0ad1d_1
  - openssl=1.1.1j=h9ed2024_0
  - path=15.1.0=py38hecd8cb5_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pip=20.2.2=py38_0
  - plac=0.9.6=py38_1
  - pycosat=0.6.3=py38h1de35cc_1
  - pycparser=2.20=py_2
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.16.0=py38h1de35cc_0
  - pysocks=1.7.1=py38_1
  - python=3.8.3=h26836e1_1
  - python-dateutil=2.8.1=py_0
  - python.app=2=py38_10
  - python_abi=3.8=1_cp38
  - pywavelets=1.1.1=py38hc7193ba_3
  - readline=8.0=h1de35cc_0
  - requests=2.24.0=py_0
  - ruamel_yaml=0.15.87=py38haf1e3a3_1
  - setuptools=49.6.0=py38_0
  - slicer=0.0.7=pyhd8ed1ab_0
  - spacy=2.3.1=py38h879752b_0
  - sqlite=3.33.0=hffcf06c_0
  - srsly=1.0.2=py38h6de7cb9_0
  - sympy=1.7.1=py38hecd8cb5_0
  - thinc=7.4.1=py38h879752b_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hb0a8c7a_0
  - tqdm=4.48.2=py_0
  - urllib3=1.25.10=py_0
  - wheel=0.35.1=py_0
  - xlrd=1.2.0=py_0
  - xz=5.2.5=h1de35cc_0
  - yaml=0.2.5=haf1e3a3_0
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.4.8=hf387650_1
  - pip:
    - absl-py==0.11.0
    - altgraph==0.17
    - anchor-exp==0.0.2.0
    - appnope==0.1.0
    - argon2-cffi==20.1.0
    - arviz==0.10.0
    - astor==0.8.1
    - astunparse==1.6.3
    - atomicwrites==1.4.0
    - attrs==18.2.0
    - backcall==0.1.0
    - backports-tempfile==1.0
    - backports-weakref==1.0.post1
    - bartpy==0.0.2
    - beautifulsoup4==4.9.0
    - bleach==3.1.4
    - boto==2.49.0
    - boto3==1.9.66
    - botocore==1.12.189
    - bqplot==0.11.5
    - cachetools==4.1.0
    - causalml==0.8.0
    - certifi==2020.6.20
    - cftime==1.3.0
    - clean-text==0.2.1
    - click==7.1.2
    - cloudpickle==1.4.1
    - convokit==2.3.2.4
    - cvxpy==1.1.7
    - cymem==2.0.2
    - cython==0.29.17
    - cytoolz==0.9.0.1
    - dask==2.16.0
    - data==0.4
    - defusedxml==0.6.0
    - deprecated==1.2.10
    - dice-ml==0.4
    - dill==0.2.9
    - distance==0.1.3
    - docutils==0.16
    - dotmap==1.3.13
    - ecos==2.0.7.post1
    - en-core-web-lg==2.3.1
    - en-core-web-sm==2.3.1
    - entrypoints==0.3
    - filelock==3.0.12
    - flatbuffers==1.12
    - ftfy==5.8
    - funcsigs==1.0.2
    - funcy==1.14
    - future==0.18.2
    - g2p-en==2.1.0
    - gast==0.3.3
    - gensim==3.8.0
    - gitdb==4.0.5
    - gitpython==3.1.0
    - glob2==0.7
    - google-api-core==1.17.0
    - google-auth==1.17.2
    - google-auth-oauthlib==0.4.1
    - google-cloud-core==1.3.0
    - google-cloud-storage==1.28.1
    - google-pasta==0.2.0
    - google-resumable-media==0.5.1
    - googleapis-common-protos==1.51.0
    - group-lasso==1.3.3
    - grpcio==1.32.0
    - gym==0.12.5
    - h5py==2.10.0
    - htmlparser==0.0.2
    - imagecodecs==2020.5.30
    - imagecodecs-lite==2019.12.3
    - imageio==2.8.0
    - importlib-metadata==1.6.0
    - inflect==4.1.0
    - ipykernel==5.1.4
    - ipython==7.13.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.17.0
    - jinja2==2.11.2
    - jmespath==0.10.0
    - json5==0.9.4
    - jsonpatch==1.25
    - jsonpointer==2.0
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.3
    - jupyter-console==6.1.0
    - jupyter-core==4.6.3
    - jupyterlab==1.2.6
    - jupyterlab-server==1.1.4
    - keras==2.4.3
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.2.0
    - latex==0.7.0
    - libarchive-c==2.9
    - lightgbm==2.3.1
    - lime==0.2.0.1
    - macholib==1.14
    - markdown==3.2.2
    - markup-py==1.12
    - markupsafe==1.1.1
    - matplotlib==3.1.3
    - minecart==0.3.0
    - mistune==0.8.4
    - more-itertools==8.3.0
    - mpld3==0.5.1
    - msgpack==0.6.1
    - msgpack-numpy==0.4.3.2
    - munch==2.5.0
    - nbconvert==5.6.1
    - nbformat==5.0.6
    - netcdf4==1.5.4
    - networkx==2.4
    - nltk==3.5
    - notebook==6.0.3
    - numexpr==2.7.1
    - numpy==1.19.5
    - oauthlib==3.1.0
    - opencv-python==4.2.0.34
    - openreview-py==1.0.16
    - opt-einsum==3.3.0
    - osqp==0.6.1
    - packaging==20.4
    - pandas==1.0.3
    - pandocfilters==1.4.2
    - parso==0.7.0
    - patsy==0.5.1
    - pdflatex==0.1.3
    - pdfminer3k==1.3.4
    - pillow==7.1.2
    - pkginfo==1.5.0.1
    - pluggy==0.13.1
    - ply==3.11
    - preshed==2.0.1
    - pretrainedmodels==0.7.4
    - progressbar2==3.51.4
    - prometheus-client==0.7.1
    - prompt-toolkit==3.0.4
    - protobuf==3.12.0
    - psutil==5.7.0
    - ptyprocess==0.6.0
    - py==1.8.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.7
    - pycocotools==2.0.0
    - pycryptodome==3.9.8
    - pydot==1.4.1
    - pydotplus==2.0.2
    - pygam==0.8.0
    - pyglet==1.5.5
    - pygments==2.6.1
    - pyinstaller==4.1.dev0
    - pyinstaller-hooks-contrib==2020.7
    - pylatexenc==2.6
    - pyldavis==2.1.2
    - pymupdf==1.17.3
    - pyreadr==0.4.1
    - pyspellchecker==0.5.2
    - pystan==2.19.1.1
    - pytest==4.6.10
    - python-graphviz==0.10.1
    - python-levenshtein==0.12.0
    - python-utils==2.4.0
    - pytorch-influence-functions==0.1.1
    - pytz==2020.1
    - pyyaml==5.3.1
    - pyzmq==18.1.1
    - qgrid==1.1.1
    - qtconsole==4.7.4
    - qtpy==1.9.0
    - regex==2020.5.14
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - s3transfer==0.1.13
    - sacremoses==0.0.43
    - scikit-image==0.17.2
    - scikit-learn==0.20.0
    - scipy==1.4.1
    - scs==2.1.2
    - seaborn==0.11.0
    - send2trash==1.5.0
    - shap==0.35.0
    - shutilwhich==1.1.0
    - six==1.14.0
    - sklearn==0.0
    - smart-open==2.1.0
    - smmap==3.0.4
    - soupsieve==2.0.1
    - stanza==1.1.1
    - statsmodels==0.11.1
    - tabulate==0.8.3
    - tempdir==0.7.1
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.7.0
    - tensorboardx==2.1
    - tensorflow==2.4.1
    - tensorflow-estimator==2.4.0
    - termcolor==1.1.0
    - terminado==0.8.3
    - testpath==0.4.4
    - textblob==0.15.3
    - tifffile==2020.5.11
    - tld==0.10
    - tokenizers==0.9.4
    - toolz==0.10.0
    - torch==1.7.1
    - torchfile==0.1.0
    - torchnet==0.0.4
    - torchtext==0.8.1
    - torchvision==0.7.0
    - tornado==6.0.4
    - traitlets==4.3.3
    - traittypes==0.2.1
    - transformers==4.2.0
    - typing-extensions==3.7.4.3
    - ujson==2.0.3
    - unidecode==1.1.1
    - visdom==0.1.8.9
    - wasabi==0.6.0
    - wcwidth==0.1.9
    - webencodings==0.5.1
    - websocket-client==0.57.0
    - werkzeug==1.0.1
    - wget==3.2
    - widgetsnbextension==3.5.1
    - wrapt==1.12.1
    - xarray==0.16.1
    - xgboost==1.1.0
    - xlsxwriter==1.2.8
    - xmltodict==0.12.0
